using NewsApiClientClasses.Constants;

namespace news_api.Extensions
{    
    public class CountryNameValuePair
    {
        public Countries key { get; set; }
        public string Name { get; set; }
    } 

    public class Constants
    {        
        //roles
        public const string RoleNameAdmin = "Admin";    

        public const string RoleNameNormalUser = "NormalUser" ;

        //policies
        public const string PolicyNameAdmin = "PolicyAdmin"; 
        public const string PolicyNameNormalAccess = "PolicyNormalAccess";   



        //constants for sorting query traces...
        public const string SortByCreatedByUser = "CreatedByUser";
        public const string SortByCreatedAt = "CreatedAt";
        public const string SortByFromDatetime = "From";
        public const string SortByToDatetime = "To";

        public const string SortByLanguage = "Language";

        public const string SortByQ = "Q";

        public const string SortByCategory = "Category";
        public const string SortByCountry = "Country";
        // ----------------------------------------------


        public static CountryNameValuePair[] CountryNames = new []{
           new CountryNameValuePair{key = Countries.AD, Name = "Andorra"},
           new CountryNameValuePair{key = Countries.AE, Name = "Emiratos Árabes Unidos"},
           new CountryNameValuePair{key = Countries.AF, Name = "Afganistán"},
           new CountryNameValuePair{key = Countries.AG, Name = "Antigua y Barbuda"},
           new CountryNameValuePair{key = Countries.AI, Name = "Anguila"},
           new CountryNameValuePair{key = Countries.AL, Name = "Albania"},
           new CountryNameValuePair{key = Countries.AM, Name = "Armenia"},
           new CountryNameValuePair{key = Countries.AN, Name = "Antillas Neerlandesas"},
           new CountryNameValuePair{key = Countries.AO, Name = "Angola"},
           new CountryNameValuePair{key = Countries.AQ, Name = "Antártida"},
           new CountryNameValuePair{key = Countries.AR, Name = "Argentina"},
           new CountryNameValuePair{key = Countries.AS, Name = "Samoa Americana"},           
           new CountryNameValuePair{key = Countries.AT, Name = "Austria"},
           new CountryNameValuePair{key = Countries.AU, Name = "Australia"},
           new CountryNameValuePair{key = Countries.AW, Name = "Aruba"},
           new CountryNameValuePair{key = Countries.AX, Name = "Islas Áland"},
           new CountryNameValuePair{key = Countries.AZ, Name = "Azerbaiyán"},
           new CountryNameValuePair{key = Countries.BA, Name = "Bosnia y Herzegovina"},
           new CountryNameValuePair{key = Countries.BB, Name = "Barbados"},
           new CountryNameValuePair{key = Countries.BD, Name = "Bangladesh"},
           new CountryNameValuePair{key = Countries.BE, Name = "Bélgica"},
           new CountryNameValuePair{key = Countries.BF, Name = "Burkina Faso"},
           new CountryNameValuePair{key = Countries.BG, Name = "Bulgaria"},
           new CountryNameValuePair{key = Countries.BH, Name = "Bahréin"},
           new CountryNameValuePair{key = Countries.BI, Name = "Burundi"},
           new CountryNameValuePair{key = Countries.BJ, Name = "Benin"},           
           new CountryNameValuePair{key = Countries.BL, Name = "San Bartolomé"},
           new CountryNameValuePair{key = Countries.BM, Name = "Bermudas"},
           new CountryNameValuePair{key = Countries.BN, Name = "Brunéi"},
           new CountryNameValuePair{key = Countries.BO, Name = "Bolivia"},
           new CountryNameValuePair{key = Countries.BR, Name = "Brasil"},
           new CountryNameValuePair{key = Countries.BS, Name = "Bahamas"},
           new CountryNameValuePair{key = Countries.BT, Name = "Bhután"},
           new CountryNameValuePair{key = Countries.BV, Name = "Isla Bouvet"},
           new CountryNameValuePair{key = Countries.BW, Name = "Botsuana"},
           new CountryNameValuePair{key = Countries.BY, Name = "Belarús"},
           new CountryNameValuePair{key = Countries.BZ, Name = "Belice"},           
           new CountryNameValuePair{key = Countries.CA, Name = "Canadá"},
           new CountryNameValuePair{key = Countries.CC, Name = "Islas Cocos"},
           new CountryNameValuePair{key = Countries.CF, Name = "República Centro-Africana"},
           new CountryNameValuePair{key = Countries.CG, Name = "Congo"},
           new CountryNameValuePair{key = Countries.CH, Name = "Suiza"},
           new CountryNameValuePair{key = Countries.CI, Name = "Costa de Marfil"},
           new CountryNameValuePair{key = Countries.CK, Name = "Islas Cook"},
           new CountryNameValuePair{key = Countries.CL, Name = "Chile"},
           new CountryNameValuePair{key = Countries.CM, Name = "Camerún"},
           new CountryNameValuePair{key = Countries.CN, Name = "China"},
           new CountryNameValuePair{key = Countries.CO, Name = "Colombia"},           
           new CountryNameValuePair{key = Countries.CR, Name = "Costa Rica"},
           new CountryNameValuePair{key = Countries.CU, Name = "Cuba"},
           new CountryNameValuePair{key = Countries.CV, Name = "Cabo Verde"},
           new CountryNameValuePair{key = Countries.CX, Name = "Islas Christmas"},
           new CountryNameValuePair{key = Countries.CY, Name = "Chipre"},
           new CountryNameValuePair{key = Countries.CZ, Name = "República Checa"},
           new CountryNameValuePair{key = Countries.DE, Name = "Alemania"},
           new CountryNameValuePair{key = Countries.DJ, Name = "Yibuti"},
           new CountryNameValuePair{key = Countries.DK, Name = "Dinamarca"},
           new CountryNameValuePair{key = Countries.DM, Name = "Domínica"},
           new CountryNameValuePair{key = Countries.DO, Name = "República Dominicana"},
           new CountryNameValuePair{key = Countries.DZ, Name = "Argel"},           
           new CountryNameValuePair{key = Countries.EC, Name = "Ecuador"},
           new CountryNameValuePair{key = Countries.EE, Name = "Estonia"},
           new CountryNameValuePair{key = Countries.EG, Name = "Egipto"},
           new CountryNameValuePair{key = Countries.EH, Name = "Sahara Occidental"},
           new CountryNameValuePair{key = Countries.ER, Name = "Eritrea"},
           new CountryNameValuePair{key = Countries.ES, Name = "España"},
           new CountryNameValuePair{key = Countries.ET, Name = "Etiopía"},
           new CountryNameValuePair{key = Countries.FI, Name = "Finlandia"},
           new CountryNameValuePair{key = Countries.FJ, Name = "Fiji"},
           new CountryNameValuePair{key = Countries.FK, Name = "Islas Malvinas"},
           new CountryNameValuePair{key = Countries.FM, Name = "Micronesia"},
           new CountryNameValuePair{key = Countries.FO, Name = "Islas Faroe"},
           new CountryNameValuePair{key = Countries.FR, Name = "Francia"},
           new CountryNameValuePair{key = Countries.GA, Name = "Gabón"},
           new CountryNameValuePair{key = Countries.GB, Name = "Reino Unido"},
           new CountryNameValuePair{key = Countries.GD, Name = "Granada"},
           new CountryNameValuePair{key = Countries.GE, Name = "Georgia"},
           new CountryNameValuePair{key = Countries.GF, Name = "Guayana Francesa"},
           new CountryNameValuePair{key = Countries.GG, Name = "Guernsey"},
           new CountryNameValuePair{key = Countries.GH, Name = "Ghana"},           
           new CountryNameValuePair{key = Countries.GI, Name = "Gibraltar"},
           new CountryNameValuePair{key = Countries.GL, Name = "Groenlandia"},
           new CountryNameValuePair{key = Countries.GM, Name = "Gambia"},
           new CountryNameValuePair{key = Countries.GN, Name = "Guinea"},
           new CountryNameValuePair{key = Countries.GP, Name = "Guadalupe"},
           new CountryNameValuePair{key = Countries.GQ, Name = "Guinea Ecuatorial"},
           new CountryNameValuePair{key = Countries.GR, Name = "Grecia"},
           new CountryNameValuePair{key = Countries.GS, Name = "Georgia del Sur e Islas Sandwich del Sur"},
           new CountryNameValuePair{key = Countries.GT, Name = "Guatemala"},
           new CountryNameValuePair{key = Countries.GU, Name = "Guam"},
           new CountryNameValuePair{key = Countries.GW, Name = "Guinea-Bissau"},
           new CountryNameValuePair{key = Countries.GY, Name = "Guayana"},
           new CountryNameValuePair{key = Countries.HK, Name = "Hong Kong"},
           new CountryNameValuePair{key = Countries.HM, Name = "Islas Heard y McDonald"},
           new CountryNameValuePair{key = Countries.HN, Name = "Honduras"},
           new CountryNameValuePair{key = Countries.HR, Name = "Croacia"},
           new CountryNameValuePair{key = Countries.HT, Name = "Haití"},
           new CountryNameValuePair{key = Countries.HU, Name = "Hungría"},           
           new CountryNameValuePair{key = Countries.ID, Name = "Indonesia"},
           new CountryNameValuePair{key = Countries.IE, Name = "Irlanda"},
           new CountryNameValuePair{key = Countries.IL, Name = "Israel"},
           new CountryNameValuePair{key = Countries.IM, Name = "Isla de Man"},
           new CountryNameValuePair{key = Countries.IN, Name = "India"},
           new CountryNameValuePair{key = Countries.IO, Name = "Territorio Británico del Océano Índico"},
           new CountryNameValuePair{key = Countries.IQ, Name = "Irak"},
           new CountryNameValuePair{key = Countries.IR, Name = "Irán"},
           new CountryNameValuePair{key = Countries.IS, Name = "Islandia"},
           new CountryNameValuePair{key = Countries.IT, Name = "Italia"},
           new CountryNameValuePair{key = Countries.JE, Name = "Jersey"},
           new CountryNameValuePair{key = Countries.JM, Name = "Jamaica"},
           new CountryNameValuePair{key = Countries.JO, Name = "Jordania"},
           new CountryNameValuePair{key = Countries.JP, Name = "Japón"},
           new CountryNameValuePair{key = Countries.KE, Name = "Kenia"},
           new CountryNameValuePair{key = Countries.KG, Name = "Kirguistán"},
           new CountryNameValuePair{key = Countries.KH, Name = "Camboya"},
           new CountryNameValuePair{key = Countries.KI, Name = "Kiribati"},
           new CountryNameValuePair{key = Countries.KM, Name = "Comoros"},
           new CountryNameValuePair{key = Countries.KN, Name = "San Cristóbal y Nieves"},
           new CountryNameValuePair{key = Countries.KP, Name = "Corea del Norte"},           
           new CountryNameValuePair{key = Countries.KR, Name = "Corea del Sur"},
           new CountryNameValuePair{key = Countries.KW, Name = "Kuwait"},
           new CountryNameValuePair{key = Countries.KY, Name = "Islas Caimán"},
           new CountryNameValuePair{key = Countries.KZ, Name = "Kazajstán"},
           new CountryNameValuePair{key = Countries.LA, Name = "Laos"},
           new CountryNameValuePair{key = Countries.LB, Name = "Líbano"},
           new CountryNameValuePair{key = Countries.LC, Name = "Santa Lucía"},
           new CountryNameValuePair{key = Countries.LI, Name = "Liechtenstein"},
           new CountryNameValuePair{key = Countries.LK, Name = "Sri Lanka"},
           new CountryNameValuePair{key = Countries.LR, Name = "Liberia"},
           new CountryNameValuePair{key = Countries.LS, Name = "Lesotho"},
           new CountryNameValuePair{key = Countries.LT, Name = "Lituania"},
           new CountryNameValuePair{key = Countries.LU, Name = "Luxemburgo"},
           new CountryNameValuePair{key = Countries.LV, Name = "Letonia"},           
           new CountryNameValuePair{key = Countries.LY, Name = "Libia"},
           new CountryNameValuePair{key = Countries.MA, Name = "Marruecos"},
           new CountryNameValuePair{key = Countries.MC, Name = "Mónaco"},
           new CountryNameValuePair{key = Countries.MD, Name = "Moldova"},
           new CountryNameValuePair{key = Countries.ME, Name = "Montenegro"},
           new CountryNameValuePair{key = Countries.MG, Name = "Madagascar"},
           new CountryNameValuePair{key = Countries.MH, Name = "Islas Marshall"},
           new CountryNameValuePair{key = Countries.MK, Name = "Macedonia"},
           new CountryNameValuePair{key = Countries.ML, Name = "Mali"},
           new CountryNameValuePair{key = Countries.MM, Name = "Myanmar"},
           new CountryNameValuePair{key = Countries.MN, Name = "Mongolia"},            
           new CountryNameValuePair{key = Countries.MO, Name = "Macao"},
           new CountryNameValuePair{key = Countries.MQ, Name = "Martinica"},
           new CountryNameValuePair{key = Countries.MR, Name = "Mauritania"},
           new CountryNameValuePair{key = Countries.MS, Name = "Montserrat"},
           new CountryNameValuePair{key = Countries.MT, Name = "Malta"},
           new CountryNameValuePair{key = Countries.MU, Name = "Mauricio"},
           new CountryNameValuePair{key = Countries.MV, Name = "Maldivas"},
           new CountryNameValuePair{key = Countries.MW, Name = "Malawi"},                      
           new CountryNameValuePair{key = Countries.MX, Name = "México"},
           new CountryNameValuePair{key = Countries.MY, Name = "Malasia"},
           new CountryNameValuePair{key = Countries.MZ, Name = "Mozambique"},
           new CountryNameValuePair{key = Countries.NA, Name = "Namibia"},
           new CountryNameValuePair{key = Countries.NC, Name = "Nueva Caledonia"},
           new CountryNameValuePair{key = Countries.NE, Name = "Níger"},
           new CountryNameValuePair{key = Countries.NF, Name = "Islas Norkfolk"},
           new CountryNameValuePair{key = Countries.NG, Name = "Nigeria"},
           new CountryNameValuePair{key = Countries.NI, Name = "Nicaragua"},
           new CountryNameValuePair{key = Countries.NL, Name = "Países Bajos"},
           new CountryNameValuePair{key = Countries.NO, Name = "Noruega"},
           new CountryNameValuePair{key = Countries.NP, Name = "Nepal"},
           new CountryNameValuePair{key = Countries.NR, Name = "Nauru"},
           new CountryNameValuePair{key = Countries.NU, Name = "Niue"},
           new CountryNameValuePair{key = Countries.NZ, Name = "Nueva Zelanda"},
           new CountryNameValuePair{key = Countries.OM, Name = "Omán"},
           new CountryNameValuePair{key = Countries.PA, Name = "Panamá"},
           new CountryNameValuePair{key = Countries.PE, Name = "Perú"},
           new CountryNameValuePair{key = Countries.PF, Name = "Polinesia Francesa"},
           new CountryNameValuePair{key = Countries.PG, Name = "Papúa Nueva Guinea"},
           new CountryNameValuePair{key = Countries.PH, Name = "Filipinas"},           
           new CountryNameValuePair{key = Countries.PK, Name = "Pakistán"},
           new CountryNameValuePair{key = Countries.PL, Name = "Polonia"},
           new CountryNameValuePair{key = Countries.PM, Name = "San Pedro y Miquelón"},
           new CountryNameValuePair{key = Countries.PN, Name = "Islas Pitcairn"},
           new CountryNameValuePair{key = Countries.PR, Name = "Puerto Rico"},
           new CountryNameValuePair{key = Countries.PS, Name = "Palestina"},
           new CountryNameValuePair{key = Countries.PT, Name = "Portugal"},
           new CountryNameValuePair{key = Countries.PW, Name = "Islas Palaos"},
           new CountryNameValuePair{key = Countries.PY, Name = "Paraguay"},
           new CountryNameValuePair{key = Countries.QA, Name = "Qatar"},
           new CountryNameValuePair{key = Countries.RE, Name = "Reunión"},
           new CountryNameValuePair{key = Countries.RO, Name = "Rumanía"}, 
           new CountryNameValuePair{key = Countries.RS, Name = "Serbia y Montenegro"},
           new CountryNameValuePair{key = Countries.RU, Name = "Rusia"},
           new CountryNameValuePair{key = Countries.RW, Name = "Ruanda"},
           new CountryNameValuePair{key = Countries.SA, Name = "Arabia Saudita"},
           new CountryNameValuePair{key = Countries.SB, Name = "Islas Solomón"},
           new CountryNameValuePair{key = Countries.SC, Name = "Seychelles"},
           new CountryNameValuePair{key = Countries.SD, Name = "Sudán"},
           new CountryNameValuePair{key = Countries.SE, Name = "Suecia"},
           new CountryNameValuePair{key = Countries.SG, Name = "Singapur"},           
           new CountryNameValuePair{key = Countries.SH, Name = "Santa Elena"},
           new CountryNameValuePair{key = Countries.SI, Name = "Eslovenia"},
           new CountryNameValuePair{key = Countries.SJ, Name = "Islas Svalbard y Jan Mayen"},
           new CountryNameValuePair{key = Countries.SK, Name = "Eslovaquia"},
           new CountryNameValuePair{key = Countries.SL, Name = "Sierra Leona"},
           new CountryNameValuePair{key = Countries.SM, Name = "San Marino"},
           new CountryNameValuePair{key = Countries.SN, Name = "Senegal"},
           new CountryNameValuePair{key = Countries.SO, Name = "Somalia"},
           new CountryNameValuePair{key = Countries.SR, Name = "Surinam"},
           new CountryNameValuePair{key = Countries.ST, Name = "Santo Tomé y Príncipe"},
           new CountryNameValuePair{key = Countries.SV, Name = "El Salvador"},           
           new CountryNameValuePair{key = Countries.SY, Name = "Siria"},
           new CountryNameValuePair{key = Countries.SZ, Name = "Suazilandia"},
           new CountryNameValuePair{key = Countries.TC, Name = "Islas Turcas y Caicos"},
           new CountryNameValuePair{key = Countries.TD, Name = "Chad"},
           new CountryNameValuePair{key = Countries.TF, Name = "Territorios Australes Franceses"},
           new CountryNameValuePair{key = Countries.TG, Name = "Togo"},
           new CountryNameValuePair{key = Countries.TH, Name = "Tailandia"},
           new CountryNameValuePair{key = Countries.TZ, Name = "Tanzania"},
           new CountryNameValuePair{key = Countries.TJ, Name = "Tayikistán"},
           new CountryNameValuePair{key = Countries.TK, Name = "Tokelau"},
           new CountryNameValuePair{key = Countries.TL, Name = "Timor-Leste"}, 

           new CountryNameValuePair{key = Countries.TM, Name = "Turkmenistán"},
           new CountryNameValuePair{key = Countries.TN, Name = "Túnez"},
           new CountryNameValuePair{key = Countries.TO, Name = "Tonga"},
           new CountryNameValuePair{key = Countries.TR, Name = "Turquía"},
           new CountryNameValuePair{key = Countries.TT, Name = "Trinidad y Tobago"},
           new CountryNameValuePair{key = Countries.TV, Name = "Tuvalu"},
           new CountryNameValuePair{key = Countries.TW, Name = "Taiwán"},           
           new CountryNameValuePair{key = Countries.UA, Name = "Ucrania"},
           new CountryNameValuePair{key = Countries.UG, Name = "Uganda"},
           new CountryNameValuePair{key = Countries.US, Name = "Estados Unidos de América"},
           new CountryNameValuePair{key = Countries.UY, Name = "Uruguay"},
           new CountryNameValuePair{key = Countries.UZ, Name = "Uzbekistán"},
           new CountryNameValuePair{key = Countries.VA, Name = "Ciudad del Vaticano"},
           new CountryNameValuePair{key = Countries.VC, Name = "San Vicente y las Granadinas"},
           new CountryNameValuePair{key = Countries.VE, Name = "Venezuela"},
           new CountryNameValuePair{key = Countries.VG, Name = "Islas Vírgenes Británicas"},
           new CountryNameValuePair{key = Countries.VI, Name = "Islas Vírgenes de los Estados Unidos de América"},
           new CountryNameValuePair{key = Countries.VN, Name = "Vietnam"},
           new CountryNameValuePair{key = Countries.VU, Name = "Vanuatu"},
           new CountryNameValuePair{key = Countries.WF, Name = "Wallis y Futuna"},
           new CountryNameValuePair{key = Countries.WS, Name = "Samoa"},
           new CountryNameValuePair{key = Countries.YE, Name = "Yemen"},
           new CountryNameValuePair{key = Countries.YT, Name = "Mayotte"},
           new CountryNameValuePair{key = Countries.ZA, Name = "Sudáfrica"}
        };        
    }
}
