using System.Linq;
using NewsApiClientClasses.Constants;
using news_api.Extensions;

namespace news_api.Extensions
{    
    public class CountryNameValuePair
    {
        public Countries Key { get; set; }
        public string Name { get; set; }
    } 

    public class LanguageNameValuePair
    {
        public Languages Key { get; set; }
        public string Name { get; set; }
    }

    public static class Constants
    {        
        //roles
        public const string RoleNameAdmin = "Admin";    

        public const string RoleNameNormalUser = "NormalUser" ;

        //policies
        public const string PolicyNameAdmin = "PolicyAdmin"; 
        public const string PolicyNameNormalAccess = "PolicyNormalAccess";   



        //constants for sorting query traces...
        public const string SortByCreatedByUser = "CreatedByUser";
        public const string SortByCreatedAt = "CreatedAt";
        public const string SortByFromDatetime = "From";
        public const string SortByToDatetime = "To";

        public const string SortByLanguage = "Language";

        public const string SortByQ = "Q";

        public const string SortByCategory = "Category";
        public const string SortByCountry = "Country";
        // ----------------------------------------------

        public static Countries UnitedStates(){
            var keyValuePair = ExtensionMethods.GetKeyValuePairsFromEnum<Countries>().SingleOrDefault(elem => elem.Value == "US");
            return (Countries)keyValuePair.Key;
        }

        public static Languages English(){
            var keyValuePair = ExtensionMethods.GetKeyValuePairsFromEnum<Languages>().SingleOrDefault(elem => elem.Value == "EN");
            return (Languages)keyValuePair.Key;
        }

        public static CountryNameValuePair[] CountryNames = new CountryNameValuePair[]{
           new CountryNameValuePair{Key = Countries.AD, Name = "Andorra"},
           new CountryNameValuePair{Key = Countries.AE, Name = "Emiratos Árabes Unidos"},
           new CountryNameValuePair{Key = Countries.AF, Name = "Afganistán"},
           new CountryNameValuePair{Key = Countries.AG, Name = "Antigua y Barbuda"},
           new CountryNameValuePair{Key = Countries.AI, Name = "Anguila"},
           new CountryNameValuePair{Key = Countries.AL, Name = "Albania"},
           new CountryNameValuePair{Key = Countries.AM, Name = "Armenia"},
           new CountryNameValuePair{Key = Countries.AN, Name = "Antillas Neerlandesas"},
           new CountryNameValuePair{Key = Countries.AO, Name = "Angola"},
           new CountryNameValuePair{Key = Countries.AQ, Name = "Antártida"},
           new CountryNameValuePair{Key = Countries.AR, Name = "Argentina"},
           new CountryNameValuePair{Key = Countries.AS, Name = "Samoa Americana"},           
           new CountryNameValuePair{Key = Countries.AT, Name = "Austria"},
           new CountryNameValuePair{Key = Countries.AU, Name = "Australia"},
           new CountryNameValuePair{Key = Countries.AW, Name = "Aruba"},
           new CountryNameValuePair{Key = Countries.AX, Name = "Islas Áland"},
           new CountryNameValuePair{Key = Countries.AZ, Name = "Azerbaiyán"},
           new CountryNameValuePair{Key = Countries.BA, Name = "Bosnia y Herzegovina"},
           new CountryNameValuePair{Key = Countries.BB, Name = "Barbados"},
           new CountryNameValuePair{Key = Countries.BD, Name = "Bangladesh"},
           new CountryNameValuePair{Key = Countries.BE, Name = "Bélgica"},
           new CountryNameValuePair{Key = Countries.BF, Name = "Burkina Faso"},
           new CountryNameValuePair{Key = Countries.BG, Name = "Bulgaria"},
           new CountryNameValuePair{Key = Countries.BH, Name = "Bahréin"},
           new CountryNameValuePair{Key = Countries.BI, Name = "Burundi"},
           new CountryNameValuePair{Key = Countries.BJ, Name = "Benin"},           
           new CountryNameValuePair{Key = Countries.BL, Name = "San Bartolomé"},
           new CountryNameValuePair{Key = Countries.BM, Name = "Bermudas"},
           new CountryNameValuePair{Key = Countries.BN, Name = "Brunéi"},
           new CountryNameValuePair{Key = Countries.BO, Name = "Bolivia"},
           new CountryNameValuePair{Key = Countries.BR, Name = "Brasil"},
           new CountryNameValuePair{Key = Countries.BS, Name = "Bahamas"},
           new CountryNameValuePair{Key = Countries.BT, Name = "Bhután"},
           new CountryNameValuePair{Key = Countries.BV, Name = "Isla Bouvet"},
           new CountryNameValuePair{Key = Countries.BW, Name = "Botsuana"},
           new CountryNameValuePair{Key = Countries.BY, Name = "Belarús"},
           new CountryNameValuePair{Key = Countries.BZ, Name = "Belice"},           
           new CountryNameValuePair{Key = Countries.CA, Name = "Canadá"},
           new CountryNameValuePair{Key = Countries.CC, Name = "Islas Cocos"},
           new CountryNameValuePair{Key = Countries.CF, Name = "República Centro-Africana"},
           new CountryNameValuePair{Key = Countries.CG, Name = "Congo"},
           new CountryNameValuePair{Key = Countries.CH, Name = "Suiza"},
           new CountryNameValuePair{Key = Countries.CI, Name = "Costa de Marfil"},
           new CountryNameValuePair{Key = Countries.CK, Name = "Islas Cook"},
           new CountryNameValuePair{Key = Countries.CL, Name = "Chile"},
           new CountryNameValuePair{Key = Countries.CM, Name = "Camerún"},
           new CountryNameValuePair{Key = Countries.CN, Name = "China"},
           new CountryNameValuePair{Key = Countries.CO, Name = "Colombia"},           
           new CountryNameValuePair{Key = Countries.CR, Name = "Costa Rica"},
           new CountryNameValuePair{Key = Countries.CU, Name = "Cuba"},
           new CountryNameValuePair{Key = Countries.CV, Name = "Cabo Verde"},
           new CountryNameValuePair{Key = Countries.CX, Name = "Islas Christmas"},
           new CountryNameValuePair{Key = Countries.CY, Name = "Chipre"},
           new CountryNameValuePair{Key = Countries.CZ, Name = "República Checa"},
           new CountryNameValuePair{Key = Countries.DE, Name = "Alemania"},
           new CountryNameValuePair{Key = Countries.DJ, Name = "Yibuti"},
           new CountryNameValuePair{Key = Countries.DK, Name = "Dinamarca"},
           new CountryNameValuePair{Key = Countries.DM, Name = "Domínica"},
           new CountryNameValuePair{Key = Countries.DO, Name = "República Dominicana"},
           new CountryNameValuePair{Key = Countries.DZ, Name = "Argel"},           
           new CountryNameValuePair{Key = Countries.EC, Name = "Ecuador"},
           new CountryNameValuePair{Key = Countries.EE, Name = "Estonia"},
           new CountryNameValuePair{Key = Countries.EG, Name = "Egipto"},
           new CountryNameValuePair{Key = Countries.EH, Name = "Sahara Occidental"},
           new CountryNameValuePair{Key = Countries.ER, Name = "Eritrea"},
           new CountryNameValuePair{Key = Countries.ES, Name = "España"},
           new CountryNameValuePair{Key = Countries.ET, Name = "Etiopía"},
           new CountryNameValuePair{Key = Countries.FI, Name = "Finlandia"},
           new CountryNameValuePair{Key = Countries.FJ, Name = "Fiji"},
           new CountryNameValuePair{Key = Countries.FK, Name = "Islas Malvinas"},
           new CountryNameValuePair{Key = Countries.FM, Name = "Micronesia"},
           new CountryNameValuePair{Key = Countries.FO, Name = "Islas Faroe"},
           new CountryNameValuePair{Key = Countries.FR, Name = "Francia"},
           new CountryNameValuePair{Key = Countries.GA, Name = "Gabón"},
           new CountryNameValuePair{Key = Countries.GB, Name = "Reino Unido"},
           new CountryNameValuePair{Key = Countries.GD, Name = "Granada"},
           new CountryNameValuePair{Key = Countries.GE, Name = "Georgia"},
           new CountryNameValuePair{Key = Countries.GF, Name = "Guayana Francesa"},
           new CountryNameValuePair{Key = Countries.GG, Name = "Guernsey"},
           new CountryNameValuePair{Key = Countries.GH, Name = "Ghana"},           
           new CountryNameValuePair{Key = Countries.GI, Name = "Gibraltar"},
           new CountryNameValuePair{Key = Countries.GL, Name = "Groenlandia"},
           new CountryNameValuePair{Key = Countries.GM, Name = "Gambia"},
           new CountryNameValuePair{Key = Countries.GN, Name = "Guinea"},
           new CountryNameValuePair{Key = Countries.GP, Name = "Guadalupe"},
           new CountryNameValuePair{Key = Countries.GQ, Name = "Guinea Ecuatorial"},
           new CountryNameValuePair{Key = Countries.GR, Name = "Grecia"},
           new CountryNameValuePair{Key = Countries.GS, Name = "Georgia del Sur e Islas Sandwich del Sur"},
           new CountryNameValuePair{Key = Countries.GT, Name = "Guatemala"},
           new CountryNameValuePair{Key = Countries.GU, Name = "Guam"},
           new CountryNameValuePair{Key = Countries.GW, Name = "Guinea-Bissau"},
           new CountryNameValuePair{Key = Countries.GY, Name = "Guayana"},
           new CountryNameValuePair{Key = Countries.HK, Name = "Hong Kong"},
           new CountryNameValuePair{Key = Countries.HM, Name = "Islas Heard y McDonald"},
           new CountryNameValuePair{Key = Countries.HN, Name = "Honduras"},
           new CountryNameValuePair{Key = Countries.HR, Name = "Croacia"},
           new CountryNameValuePair{Key = Countries.HT, Name = "Haití"},
           new CountryNameValuePair{Key = Countries.HU, Name = "Hungría"},           
           new CountryNameValuePair{Key = Countries.ID, Name = "Indonesia"},
           new CountryNameValuePair{Key = Countries.IE, Name = "Irlanda"},
           new CountryNameValuePair{Key = Countries.IL, Name = "Israel"},
           new CountryNameValuePair{Key = Countries.IM, Name = "Isla de Man"},
           new CountryNameValuePair{Key = Countries.IN, Name = "India"},
           new CountryNameValuePair{Key = Countries.IO, Name = "Territorio Británico del Océano Índico"},
           new CountryNameValuePair{Key = Countries.IQ, Name = "Irak"},
           new CountryNameValuePair{Key = Countries.IR, Name = "Irán"},
           new CountryNameValuePair{Key = Countries.IS, Name = "Islandia"},
           new CountryNameValuePair{Key = Countries.IT, Name = "Italia"},
           new CountryNameValuePair{Key = Countries.JE, Name = "Jersey"},
           new CountryNameValuePair{Key = Countries.JM, Name = "Jamaica"},
           new CountryNameValuePair{Key = Countries.JO, Name = "Jordania"},
           new CountryNameValuePair{Key = Countries.JP, Name = "Japón"},
           new CountryNameValuePair{Key = Countries.KE, Name = "Kenia"},
           new CountryNameValuePair{Key = Countries.KG, Name = "Kirguistán"},
           new CountryNameValuePair{Key = Countries.KH, Name = "Camboya"},
           new CountryNameValuePair{Key = Countries.KI, Name = "Kiribati"},
           new CountryNameValuePair{Key = Countries.KM, Name = "Comoros"},
           new CountryNameValuePair{Key = Countries.KN, Name = "San Cristóbal y Nieves"},
           new CountryNameValuePair{Key = Countries.KP, Name = "Corea del Norte"},           
           new CountryNameValuePair{Key = Countries.KR, Name = "Corea del Sur"},
           new CountryNameValuePair{Key = Countries.KW, Name = "Kuwait"},
           new CountryNameValuePair{Key = Countries.KY, Name = "Islas Caimán"},
           new CountryNameValuePair{Key = Countries.KZ, Name = "Kazajstán"},
           new CountryNameValuePair{Key = Countries.LA, Name = "Laos"},
           new CountryNameValuePair{Key = Countries.LB, Name = "Líbano"},
           new CountryNameValuePair{Key = Countries.LC, Name = "Santa Lucía"},
           new CountryNameValuePair{Key = Countries.LI, Name = "Liechtenstein"},
           new CountryNameValuePair{Key = Countries.LK, Name = "Sri Lanka"},
           new CountryNameValuePair{Key = Countries.LR, Name = "Liberia"},
           new CountryNameValuePair{Key = Countries.LS, Name = "Lesotho"},
           new CountryNameValuePair{Key = Countries.LT, Name = "Lituania"},
           new CountryNameValuePair{Key = Countries.LU, Name = "Luxemburgo"},
           new CountryNameValuePair{Key = Countries.LV, Name = "Letonia"},           
           new CountryNameValuePair{Key = Countries.LY, Name = "Libia"},
           new CountryNameValuePair{Key = Countries.MA, Name = "Marruecos"},
           new CountryNameValuePair{Key = Countries.MC, Name = "Mónaco"},
           new CountryNameValuePair{Key = Countries.MD, Name = "Moldova"},
           new CountryNameValuePair{Key = Countries.ME, Name = "Montenegro"},
           new CountryNameValuePair{Key = Countries.MG, Name = "Madagascar"},
           new CountryNameValuePair{Key = Countries.MH, Name = "Islas Marshall"},
           new CountryNameValuePair{Key = Countries.MK, Name = "Macedonia"},
           new CountryNameValuePair{Key = Countries.ML, Name = "Mali"},
           new CountryNameValuePair{Key = Countries.MM, Name = "Myanmar"},
           new CountryNameValuePair{Key = Countries.MN, Name = "Mongolia"},            
           new CountryNameValuePair{Key = Countries.MO, Name = "Macao"},
           new CountryNameValuePair{Key = Countries.MQ, Name = "Martinica"},
           new CountryNameValuePair{Key = Countries.MR, Name = "Mauritania"},
           new CountryNameValuePair{Key = Countries.MS, Name = "Montserrat"},
           new CountryNameValuePair{Key = Countries.MT, Name = "Malta"},
           new CountryNameValuePair{Key = Countries.MU, Name = "Mauricio"},
           new CountryNameValuePair{Key = Countries.MV, Name = "Maldivas"},
           new CountryNameValuePair{Key = Countries.MW, Name = "Malawi"},                      
           new CountryNameValuePair{Key = Countries.MX, Name = "México"},
           new CountryNameValuePair{Key = Countries.MY, Name = "Malasia"},
           new CountryNameValuePair{Key = Countries.MZ, Name = "Mozambique"},
           new CountryNameValuePair{Key = Countries.NA, Name = "Namibia"},
           new CountryNameValuePair{Key = Countries.NC, Name = "Nueva Caledonia"},
           new CountryNameValuePair{Key = Countries.NE, Name = "Níger"},
           new CountryNameValuePair{Key = Countries.NF, Name = "Islas Norkfolk"},
           new CountryNameValuePair{Key = Countries.NG, Name = "Nigeria"},
           new CountryNameValuePair{Key = Countries.NI, Name = "Nicaragua"},
           new CountryNameValuePair{Key = Countries.NL, Name = "Países Bajos"},
           new CountryNameValuePair{Key = Countries.NO, Name = "Noruega"},
           new CountryNameValuePair{Key = Countries.NP, Name = "Nepal"},
           new CountryNameValuePair{Key = Countries.NR, Name = "Nauru"},
           new CountryNameValuePair{Key = Countries.NU, Name = "Niue"},
           new CountryNameValuePair{Key = Countries.NZ, Name = "Nueva Zelanda"},
           new CountryNameValuePair{Key = Countries.OM, Name = "Omán"},
           new CountryNameValuePair{Key = Countries.PA, Name = "Panamá"},
           new CountryNameValuePair{Key = Countries.PE, Name = "Perú"},
           new CountryNameValuePair{Key = Countries.PF, Name = "Polinesia Francesa"},
           new CountryNameValuePair{Key = Countries.PG, Name = "Papúa Nueva Guinea"},
           new CountryNameValuePair{Key = Countries.PH, Name = "Filipinas"},           
           new CountryNameValuePair{Key = Countries.PK, Name = "Pakistán"},
           new CountryNameValuePair{Key = Countries.PL, Name = "Polonia"},
           new CountryNameValuePair{Key = Countries.PM, Name = "San Pedro y Miquelón"},
           new CountryNameValuePair{Key = Countries.PN, Name = "Islas Pitcairn"},
           new CountryNameValuePair{Key = Countries.PR, Name = "Puerto Rico"},
           new CountryNameValuePair{Key = Countries.PS, Name = "Palestina"},
           new CountryNameValuePair{Key = Countries.PT, Name = "Portugal"},
           new CountryNameValuePair{Key = Countries.PW, Name = "Islas Palaos"},
           new CountryNameValuePair{Key = Countries.PY, Name = "Paraguay"},
           new CountryNameValuePair{Key = Countries.QA, Name = "Qatar"},
           new CountryNameValuePair{Key = Countries.RE, Name = "Reunión"},
           new CountryNameValuePair{Key = Countries.RO, Name = "Rumanía"}, 
           new CountryNameValuePair{Key = Countries.RS, Name = "Serbia y Montenegro"},
           new CountryNameValuePair{Key = Countries.RU, Name = "Rusia"},
           new CountryNameValuePair{Key = Countries.RW, Name = "Ruanda"},
           new CountryNameValuePair{Key = Countries.SA, Name = "Arabia Saudita"},
           new CountryNameValuePair{Key = Countries.SB, Name = "Islas Solomón"},
           new CountryNameValuePair{Key = Countries.SC, Name = "Seychelles"},
           new CountryNameValuePair{Key = Countries.SD, Name = "Sudán"},
           new CountryNameValuePair{Key = Countries.SE, Name = "Suecia"},
           new CountryNameValuePair{Key = Countries.SG, Name = "Singapur"},           
           new CountryNameValuePair{Key = Countries.SH, Name = "Santa Elena"},
           new CountryNameValuePair{Key = Countries.SI, Name = "Eslovenia"},
           new CountryNameValuePair{Key = Countries.SJ, Name = "Islas Svalbard y Jan Mayen"},
           new CountryNameValuePair{Key = Countries.SK, Name = "Eslovaquia"},
           new CountryNameValuePair{Key = Countries.SL, Name = "Sierra Leona"},
           new CountryNameValuePair{Key = Countries.SM, Name = "San Marino"},
           new CountryNameValuePair{Key = Countries.SN, Name = "Senegal"},
           new CountryNameValuePair{Key = Countries.SO, Name = "Somalia"},
           new CountryNameValuePair{Key = Countries.SR, Name = "Surinam"},
           new CountryNameValuePair{Key = Countries.ST, Name = "Santo Tomé y Príncipe"},
           new CountryNameValuePair{Key = Countries.SV, Name = "El Salvador"},           
           new CountryNameValuePair{Key = Countries.SY, Name = "Siria"},
           new CountryNameValuePair{Key = Countries.SZ, Name = "Suazilandia"},
           new CountryNameValuePair{Key = Countries.TC, Name = "Islas Turcas y Caicos"},
           new CountryNameValuePair{Key = Countries.TD, Name = "Chad"},
           new CountryNameValuePair{Key = Countries.TF, Name = "Territorios Australes Franceses"},
           new CountryNameValuePair{Key = Countries.TG, Name = "Togo"},
           new CountryNameValuePair{Key = Countries.TH, Name = "Tailandia"},
           new CountryNameValuePair{Key = Countries.TZ, Name = "Tanzania"},
           new CountryNameValuePair{Key = Countries.TJ, Name = "Tayikistán"},
           new CountryNameValuePair{Key = Countries.TK, Name = "Tokelau"},
           new CountryNameValuePair{Key = Countries.TL, Name = "Timor-Leste"}, 
           new CountryNameValuePair{Key = Countries.TM, Name = "Turkmenistán"},
           new CountryNameValuePair{Key = Countries.TN, Name = "Túnez"},
           new CountryNameValuePair{Key = Countries.TO, Name = "Tonga"},
           new CountryNameValuePair{Key = Countries.TR, Name = "Turquía"},
           new CountryNameValuePair{Key = Countries.TT, Name = "Trinidad y Tobago"},
           new CountryNameValuePair{Key = Countries.TV, Name = "Tuvalu"},
           new CountryNameValuePair{Key = Countries.TW, Name = "Taiwán"},           
           new CountryNameValuePair{Key = Countries.UA, Name = "Ucrania"},
           new CountryNameValuePair{Key = Countries.UG, Name = "Uganda"},
           new CountryNameValuePair{Key = Countries.US, Name = "Estados Unidos de América"},
           new CountryNameValuePair{Key = Countries.UY, Name = "Uruguay"},
           new CountryNameValuePair{Key = Countries.UZ, Name = "Uzbekistán"},
           new CountryNameValuePair{Key = Countries.VA, Name = "Ciudad del Vaticano"},
           new CountryNameValuePair{Key = Countries.VC, Name = "San Vicente y las Granadinas"},
           new CountryNameValuePair{Key = Countries.VE, Name = "Venezuela"},
           new CountryNameValuePair{Key = Countries.VG, Name = "Islas Vírgenes Británicas"},
           new CountryNameValuePair{Key = Countries.VI, Name = "Islas Vírgenes de los Estados Unidos de América"},
           new CountryNameValuePair{Key = Countries.VN, Name = "Vietnam"},
           new CountryNameValuePair{Key = Countries.VU, Name = "Vanuatu"},
           new CountryNameValuePair{Key = Countries.WF, Name = "Wallis y Futuna"},
           new CountryNameValuePair{Key = Countries.WS, Name = "Samoa"},
           new CountryNameValuePair{Key = Countries.YE, Name = "Yemen"},
           new CountryNameValuePair{Key = Countries.YT, Name = "Mayotte"},
           new CountryNameValuePair{Key = Countries.ZA, Name = "Sudáfrica"}
        };

        public static string GetCountryNameByEnum(Countries countryEnum){
            var elem = CountryNames.SingleOrDefault(item => item.Key == countryEnum);
            return elem?.Name ?? countryEnum.ToString();
        }    


        public static LanguageNameValuePair[] LanguageNames = new LanguageNameValuePair[]{
            new LanguageNameValuePair{Key = Languages.AA, Name = "afar"},
            new LanguageNameValuePair{Key = Languages.AB, Name = "abjaso"},
            new LanguageNameValuePair{Key = Languages.AE, Name = "avéstico"},
            new LanguageNameValuePair{Key = Languages.AF, Name = "afrikaans"},
            new LanguageNameValuePair{Key = Languages.AK, Name = "akano"},
            new LanguageNameValuePair{Key = Languages.AM, Name = "amárico"},
            new LanguageNameValuePair{Key = Languages.AN, Name = "aragonés"},
            new LanguageNameValuePair{Key = Languages.AR, Name = "árabe"},
            new LanguageNameValuePair{Key = Languages.AS, Name = "asamés"},
            new LanguageNameValuePair{Key = Languages.AV, Name = "avar"},
            new LanguageNameValuePair{Key = Languages.AY, Name = "aimara"},
            new LanguageNameValuePair{Key = Languages.AZ, Name = "azerí"},
            new LanguageNameValuePair{Key = Languages.BA, Name = "baskir"},
            new LanguageNameValuePair{Key = Languages.BE, Name = "bielorruso"},
            new LanguageNameValuePair{Key = Languages.BG, Name = "búlgaro"},
            new LanguageNameValuePair{Key = Languages.BH, Name = "bhojpurí"},
            new LanguageNameValuePair{Key = Languages.BI, Name = "bislama"},
            new LanguageNameValuePair{Key = Languages.BM, Name = "bambara"},
            new LanguageNameValuePair{Key = Languages.BN, Name = "bengalí"},
            new LanguageNameValuePair{Key = Languages.BO, Name = "tibetano"},
            new LanguageNameValuePair{Key = Languages.BR, Name = "bretón"},
            new LanguageNameValuePair{Key = Languages.BS, Name = "bosnio"},
            new LanguageNameValuePair{Key = Languages.CA, Name = "catalán"},
            new LanguageNameValuePair{Key = Languages.CE, Name = "checheno"},
            new LanguageNameValuePair{Key = Languages.CH, Name = "chamorro"},
            new LanguageNameValuePair{Key = Languages.CO, Name = "corso"},
            new LanguageNameValuePair{Key = Languages.CR, Name = "cree"},
            new LanguageNameValuePair{Key = Languages.CS, Name = "checo"},
            new LanguageNameValuePair{Key = Languages.CU, Name = "eslavo eclesiástico antiguo"},
            new LanguageNameValuePair{Key = Languages.CV, Name = "chuvasio"},
            new LanguageNameValuePair{Key = Languages.CY, Name = "galés"},
            new LanguageNameValuePair{Key = Languages.DA, Name = "danés"},
            new LanguageNameValuePair{Key = Languages.DE, Name = "alemán"},
            new LanguageNameValuePair{Key = Languages.DV, Name = "maldivo"},
            new LanguageNameValuePair{Key = Languages.DZ, Name = "dzongkha"},
            new LanguageNameValuePair{Key = Languages.EE, Name = "ewe"},
            new LanguageNameValuePair{Key = Languages.EL, Name = "griego"},
            new LanguageNameValuePair{Key = Languages.EN, Name = "inglés"},
            new LanguageNameValuePair{Key = Languages.EO, Name = "esperanto"},
            new LanguageNameValuePair{Key = Languages.ES, Name = "español"},
            new LanguageNameValuePair{Key = Languages.ET, Name = "estonio"},
            new LanguageNameValuePair{Key = Languages.EU, Name = "vascuence"},
            new LanguageNameValuePair{Key = Languages.FA, Name = "persa"},
            new LanguageNameValuePair{Key = Languages.FF, Name = "fula"},
            new LanguageNameValuePair{Key = Languages.FI, Name = "finés"},
            new LanguageNameValuePair{Key = Languages.FJ, Name = "fijiano"},
            new LanguageNameValuePair{Key = Languages.FO, Name = "feroés"},
            new LanguageNameValuePair{Key = Languages.FY, Name = "frisón"},
            new LanguageNameValuePair{Key = Languages.GA, Name = "irlandés"},
            new LanguageNameValuePair{Key = Languages.GD, Name = "gaélico escocés"},
            new LanguageNameValuePair{Key = Languages.GL, Name = "gallego"},
            new LanguageNameValuePair{Key = Languages.GN, Name = "guaraní"},
            new LanguageNameValuePair{Key = Languages.GU, Name = "guyaratí"},
            new LanguageNameValuePair{Key = Languages.GV, Name = "manés"},
            new LanguageNameValuePair{Key = Languages.HA, Name = "hausa"},
            new LanguageNameValuePair{Key = Languages.HE, Name = "hebreo"},
            new LanguageNameValuePair{Key = Languages.HI, Name = "hindi"},
            new LanguageNameValuePair{Key = Languages.HO, Name = "hiri motu"},
            new LanguageNameValuePair{Key = Languages.HR, Name = "croata"},
            new LanguageNameValuePair{Key = Languages.HT, Name = "haitiano"},
            new LanguageNameValuePair{Key = Languages.HU, Name = "húngaro"},
            new LanguageNameValuePair{Key = Languages.HY, Name = "armenio"},
            new LanguageNameValuePair{Key = Languages.HZ, Name = "herero"},
            new LanguageNameValuePair{Key = Languages.IA, Name = "interlingua"},
            new LanguageNameValuePair{Key = Languages.ID, Name = "indonesio"},
            new LanguageNameValuePair{Key = Languages.IE, Name = "occidental"},
            new LanguageNameValuePair{Key = Languages.IG, Name = "igbo"},
            new LanguageNameValuePair{Key = Languages.II, Name = "yi de Sichuán"},
            new LanguageNameValuePair{Key = Languages.IK, Name = "inupiaq"},
            new LanguageNameValuePair{Key = Languages.IO, Name = "ido"},
            new LanguageNameValuePair{Key = Languages.IS, Name = "islandés"},
            new LanguageNameValuePair{Key = Languages.IT, Name = "italiano"},
            new LanguageNameValuePair{Key = Languages.IU, Name = "inuktitut"},
            new LanguageNameValuePair{Key = Languages.JA, Name = "japonés"},
            new LanguageNameValuePair{Key = Languages.JV, Name = "javanés"},
            new LanguageNameValuePair{Key = Languages.KA, Name = "georgiano"},
            new LanguageNameValuePair{Key = Languages.KG, Name = "kongo"},
            new LanguageNameValuePair{Key = Languages.KI, Name = "kikuyu"},
            new LanguageNameValuePair{Key = Languages.KJ, Name = "kuanyama"},
            new LanguageNameValuePair{Key = Languages.KK, Name = "kazajo (o kazajio)"},
            new LanguageNameValuePair{Key = Languages.KL, Name = "groenlandés (o kalaallisut)"},
            new LanguageNameValuePair{Key = Languages.KM, Name = "camboyano"},
            new LanguageNameValuePair{Key = Languages.KN, Name = "canarés"},
            new LanguageNameValuePair{Key = Languages.KO, Name = "coreano"},
            new LanguageNameValuePair{Key = Languages.KR, Name = "kanuri"},
            new LanguageNameValuePair{Key = Languages.KS, Name = "cachemiro"},
            new LanguageNameValuePair{Key = Languages.KU, Name = "kurdo"},
            new LanguageNameValuePair{Key = Languages.KV, Name = "komi"},
            new LanguageNameValuePair{Key = Languages.KW, Name = "córnico"},
            new LanguageNameValuePair{Key = Languages.KY, Name = "kirguís"},
            new LanguageNameValuePair{Key = Languages.LA, Name = "latín"},
            new LanguageNameValuePair{Key = Languages.LB, Name = "luxemburgués"},
            new LanguageNameValuePair{Key = Languages.LG, Name = "luganda"},
            new LanguageNameValuePair{Key = Languages.LI, Name = "limburgués"},
            new LanguageNameValuePair{Key = Languages.LN, Name = "lingala"},
            new LanguageNameValuePair{Key = Languages.LO, Name = "lao"},
            new LanguageNameValuePair{Key = Languages.LT, Name = "lituano"},
            new LanguageNameValuePair{Key = Languages.LU, Name = "luba-katanga"},
            new LanguageNameValuePair{Key = Languages.LV, Name = "letón"},
            new LanguageNameValuePair{Key = Languages.MG, Name = "malgache (o malagasy)"},
            new LanguageNameValuePair{Key = Languages.MH, Name = "marshalés"},
            new LanguageNameValuePair{Key = Languages.MI, Name = "maorí"},
            new LanguageNameValuePair{Key = Languages.MK, Name = "macedonio"},
            new LanguageNameValuePair{Key = Languages.ML, Name = "malayalam"},
            new LanguageNameValuePair{Key = Languages.MN, Name = "mongol"},
            new LanguageNameValuePair{Key = Languages.MO, Name = "moldavo"},
            new LanguageNameValuePair{Key = Languages.MR, Name = "maratí"},
            new LanguageNameValuePair{Key = Languages.MS, Name = "malayo"},
            new LanguageNameValuePair{Key = Languages.MT, Name = "maltés"},
            new LanguageNameValuePair{Key = Languages.MY, Name = "birmano"},
            new LanguageNameValuePair{Key = Languages.NA, Name = "nauruano"},
            new LanguageNameValuePair{Key = Languages.NB, Name = "noruego bokmål"},
            new LanguageNameValuePair{Key = Languages.ND, Name = "ndebele del norte"},
            new LanguageNameValuePair{Key = Languages.NE, Name = "nepalí"},
            new LanguageNameValuePair{Key = Languages.NG, Name = "ndonga"},
            new LanguageNameValuePair{Key = Languages.NL, Name = "neerlandés"},
            new LanguageNameValuePair{Key = Languages.NN, Name = "nynorsk"},
            new LanguageNameValuePair{Key = Languages.NO, Name = "noruego"},
            new LanguageNameValuePair{Key = Languages.NR, Name = "ndebele del sur"},
            new LanguageNameValuePair{Key = Languages.NV, Name = "navajo"},
            new LanguageNameValuePair{Key = Languages.NY, Name = "chichewa"},
            new LanguageNameValuePair{Key = Languages.OC, Name = "occitano"},
            new LanguageNameValuePair{Key = Languages.OJ, Name = "ojibwa"},
            new LanguageNameValuePair{Key = Languages.OM, Name = "oromo"},
            new LanguageNameValuePair{Key = Languages.OR, Name = "oriya"},
            new LanguageNameValuePair{Key = Languages.OS, Name = "osético"},
            new LanguageNameValuePair{Key = Languages.PA, Name = "panyabí"},
            new LanguageNameValuePair{Key = Languages.PI, Name = "pali"},
            new LanguageNameValuePair{Key = Languages.PL, Name = "polaco"},
            new LanguageNameValuePair{Key = Languages.PS, Name = "pastú"},
            new LanguageNameValuePair{Key = Languages.PT, Name = "portugués"},
            new LanguageNameValuePair{Key = Languages.QU, Name = "quechua"},
            new LanguageNameValuePair{Key = Languages.RM, Name = "retorrománico"},
            new LanguageNameValuePair{Key = Languages.RN, Name = "kirundi"},
            new LanguageNameValuePair{Key = Languages.RO, Name = "rumano"},
            new LanguageNameValuePair{Key = Languages.RU, Name = "ruso"},
            new LanguageNameValuePair{Key = Languages.RW, Name = "ruandés"},
            new LanguageNameValuePair{Key = Languages.SA, Name = "sánscrito"},
            new LanguageNameValuePair{Key = Languages.SC, Name = "sardo"},
            new LanguageNameValuePair{Key = Languages.SD, Name = "sindhi"},
            new LanguageNameValuePair{Key = Languages.SE, Name = "sami septentrional"},
            new LanguageNameValuePair{Key = Languages.SG, Name = "sango"},
            new LanguageNameValuePair{Key = Languages.SI, Name = "cingalés"},
            new LanguageNameValuePair{Key = Languages.SK, Name = "eslovaco"},
            new LanguageNameValuePair{Key = Languages.SL, Name = "esloveno"},
            new LanguageNameValuePair{Key = Languages.SM, Name = "samoano"},
            new LanguageNameValuePair{Key = Languages.SN, Name = "shona"},
            new LanguageNameValuePair{Key = Languages.SO, Name = "somalí"},
            new LanguageNameValuePair{Key = Languages.SQ, Name = "albanés"},
            new LanguageNameValuePair{Key = Languages.SR, Name = "serbio"},
            new LanguageNameValuePair{Key = Languages.SS, Name = "suazi (swati o siSwati)"},
            new LanguageNameValuePair{Key = Languages.ST, Name = "sesotho"},
            new LanguageNameValuePair{Key = Languages.SU, Name = "sundanés"},
            new LanguageNameValuePair{Key = Languages.SV, Name = "sueco"},
            new LanguageNameValuePair{Key = Languages.SW, Name = "suajili"},
            new LanguageNameValuePair{Key = Languages.TA, Name = "tamil"},
            new LanguageNameValuePair{Key = Languages.TE, Name = "telugú"},
            new LanguageNameValuePair{Key = Languages.TG, Name = "tayiko"},
            new LanguageNameValuePair{Key = Languages.TH, Name = "tailandés"},
            new LanguageNameValuePair{Key = Languages.TI, Name = "tigriña"},
            new LanguageNameValuePair{Key = Languages.TK, Name = "turcomano"},
            new LanguageNameValuePair{Key = Languages.TL, Name = "tagalo"},
            new LanguageNameValuePair{Key = Languages.TN, Name = "setsuana"},
            new LanguageNameValuePair{Key = Languages.TO, Name = "tongano"},
            new LanguageNameValuePair{Key = Languages.TR, Name = "turco"},
            new LanguageNameValuePair{Key = Languages.TS, Name = "tsonga"},
            new LanguageNameValuePair{Key = Languages.TT, Name = "tártaro"},
            new LanguageNameValuePair{Key = Languages.TW, Name = "twi"},
            new LanguageNameValuePair{Key = Languages.TY, Name = "tahitiano"},
            new LanguageNameValuePair{Key = Languages.UG, Name = "uigur"},
            new LanguageNameValuePair{Key = Languages.UK, Name = "ucraniano"},
            new LanguageNameValuePair{Key = Languages.UR, Name = "urdu"},
            new LanguageNameValuePair{Key = Languages.UZ, Name = "uzbeko"},
            new LanguageNameValuePair{Key = Languages.VE, Name = "venda"},
            new LanguageNameValuePair{Key = Languages.VI, Name = "vietnamita"},
            new LanguageNameValuePair{Key = Languages.VO, Name = "volapük"},
            new LanguageNameValuePair{Key = Languages.WA, Name = "valón"},
            new LanguageNameValuePair{Key = Languages.WO, Name = "wolof"},
            new LanguageNameValuePair{Key = Languages.XH, Name = "xhosa"},
            new LanguageNameValuePair{Key = Languages.YI, Name = "yídish (o yiddish)"},
            new LanguageNameValuePair{Key = Languages.YO, Name = "yoruba"},
            new LanguageNameValuePair{Key = Languages.ZA, Name = "chuan (o zhuang)"},
            new LanguageNameValuePair{Key = Languages.ZH, Name = "chino"},
            new LanguageNameValuePair{Key = Languages.ZU, Name = "zulú"}
        };

        public static string GetLanguageNameByEnum(Languages languageEnum){
            var elem = LanguageNames.SingleOrDefault(item => item.Key == languageEnum);
            return elem?.Name ?? languageEnum.ToString();
        } 
    }
}
